### ISSUE TITLE
add Microsoft login to liquid launcher [FETURE]

### ISSUE THREAD

**Issue by kaidacoder** [CCBlueX/LiquidLauncher#112]
### Describe your feature request.

i haven't been using liquid bounce for to long but i think it is a bit repetitive to always have to download and change the mods and i would really love to have that feature implemented into liquid launcher

### Additional context

PLSSSS

**Comment by 1zun4** [comment]
Done.

Implemented https://github.com/CCBlueX/LiquidLauncher/commit/02c9aba61992bcdbd5f3046640d6a242cddf8dde
https://www.youtube.com/watch?v=Y4XnEXqEjI0

**Comment by kaidacoder** [comment]
THANK YOU SO MUCH YOU DONT KNOW HOW HAPPY I AM

**Comment by kaidacoder** [comment]
hey where can you download this

**Comment by kaidacoder** [comment]
sorry to ask
i just cant seem to find it
