### ISSUE TITLE
Suggestion #1 "forks"

### ISSUE THREAD

**Issue by opZywl** [CCBlueX/LiquidLauncher#118]
it would be nice if we could use custom forks without having to create launcher forks, for example a global community where we put the github link or something and it was possible to start in liquidlaucher

Why implement this <?>

It would be fun and also how many people use forks is a way to find new forks and motivate new forks
I could create a record of forks and a check for forks that follow the terms ccbluex well I don't know much but it would be good and you would be able to check and those forks that don't follow would not be possible but a request request to add forks in laucher and you would have controls such as multiplayer servers where mojang itself is not responsible for servers but punishes those who do not follow

i believe i would get the community active and can check and try out forks and report to ccbluex (this suggestion is not for all forks to do this) but i say those forks that qualify as a rank scale would be a good match / and of course you can do that if you want

**Comment by 1zun4** [comment]
I thought about this suggestion a long time ago when I started making this launcher. It would be no issue to provide fork-made builds, but we have to make sure they are from reliable sources. Means we have to make sure that the build inside the launcher is the original build signed from GitHub. I might work on this soon.
