### ISSUE TITLE
[bug] LiquidLauncher not compiling even when using nightly tool chain

### ISSUE THREAD

**Issue by kaidacoder** [CCBlueX/LiquidLauncher#125]
warning: unused import: `std::sync::Mutex`
 --> src\main.rs:9:5
  |
9 | use std::sync::Mutex;
  |     ^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `anyhow`
  --> src\main.rs:11:14
   |
11 | use anyhow::{anyhow, Result};
   |              ^^^^^^

warning: unused import: `minceraft::auth`
  --> src\main.rs:13:5
   |
13 | use minceraft::auth;
   |     ^^^^^^^^^^^^^^^

warning: unused import: `directories::ProjectDirs`
 --> src\app\gui.rs:8:5
  |
8 | use directories::ProjectDirs;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `tokio::task`
  --> src\app\gui.rs:16:5
   |
16 | use tokio::task;
   |     ^^^^^^^^^^^

warning: unused import: `directories::ProjectDirs`
 --> src\app\cli.rs:4:5
  |
4 | use directories::ProjectDirs;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `RefreshKind`
  --> src\app\cli.rs:14:15
   |
14 | use sysinfo::{RefreshKind, SystemExt};
   |               ^^^^^^^^^^^

warning: unused import: `std::fs::File`
 --> src\minecraft\service.rs:2:5
  |
2 | use std::fs::File;
  |     ^^^^^^^^^^^^^

warning: unused import: `std::path::Path`
 --> src\minecraft\service.rs:3:5
  |
3 | use std::path::Path;
  |     ^^^^^^^^^^^^^^^

warning: unused import: `Build`
 --> src\minecraft\prelauncher.rs:8:23
  |
8 | use crate::app::api::{Build, ApiEndpoints, LaunchManifest, LoaderSubsystem, ModSource, LoaderMod};
  |                       ^^^^^

warning: unreachable statement
  --> src\main.rs:50:9
   |
47 |                 return Ok(());
   |                 ------------- any code following this expression is unreachable
...
50 |         eprintln!("This build does not support CLI.");
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unreachable statement
   |
   = note: `#[warn(unreachable_code)]` on by default
   = note: this warning originates in the macro `eprintln` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unreachable statement
  --> src\main.rs:60:5
   |
57 |             return Ok(());
   |             ------------- any code following this expression is unreachable
...
60 |     eprintln!("This build does not support GUI.");
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unreachable statement
   |
   = note: this warning originates in the macro `eprintln` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unused variable: `value`
  --> src\app\cli.rs:87:18
   |
87 | fn handle_stdout(value: &(), data: &[u8]) -> Result<()> {
   |                  ^^^^^ help: if this is intentional, prefix it with an underscore: `_value`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `value`
  --> src\app\cli.rs:94:20
   |
94 | fn handle_progress(value: &(), progress_update: ProgressUpdate) -> Result<()> {
   |                    ^^^^^ help: if this is intentional, prefix it with an underscore: `_value`

warning: unused variable: `progress_update`
  --> src\app\cli.rs:94:32
   |
94 | fn handle_progress(value: &(), progress_update: ProgressUpdate) -> Result<()> {
   |                                ^^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_progress_update`

warning: unused variable: `mod_cache_path`
  --> src\minecraft\prelauncher.rs:69:9
   |
69 |     let mod_cache_path = data.join("mod_cache");
   |         ^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_mod_cache_path`

warning: unused variable: `github_release_data`
  --> src\updater\mod.rs:41:25
   |
41 | async fn install_update(github_release_data: GitHubReleaseData) {
   |                         ^^^^^^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_github_release_data`

warning: field `constant_data` is never read
  --> src\app\gui.rs:34:5
   |
33 | struct EventHandler {
   |        ------------ field in this struct
34 |     constant_data: Arc<ConstantLauncherData>,
   |     ^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: field `user` is never read
  --> src\minecraft\service.rs:78:9
   |
77 |     struct AuthenticateResponse {
   |            -------------------- field in this struct
78 |         user: Option<AuthenticateUser>,
   |         ^^^^

warning: variants `InvalidLauncherManifest` and `InvalidResponse` are never constructed
  --> src\error.rs:8:5
   |
4  | pub enum LauncherError {
   |          ------------- variants in this enum
...
8  |     InvalidLauncherManifest(String),
   |     ^^^^^^^^^^^^^^^^^^^^^^^
...
12 |     InvalidResponse(String),
   |     ^^^^^^^^^^^^^^^
   |
   = note: `LauncherError` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis

warning: function `install_update` is never used
  --> src\updater\mod.rs:41:10
   |
41 | async fn install_update(github_release_data: GitHubReleaseData) {
   |          ^^^^^^^^^^^^^^

warning: `liquidlauncher` (bin "liquidlauncher") generated 21 warnings (run `cargo fix --bin "liquidlauncher"` to apply 15 suggestions)
    Finished release [optimized] target(s) in 2.21s

**Comment by kaidacoder** [comment]
so what must i do

**Comment by 1zun4** [comment]
???

**Comment by kaidacoder** [comment]
when it is compiled how do i open it

**Comment by kaidacoder** [comment]
@1zun4 how do i open it

**Comment by 1zun4** [comment]
The compiled exe is located in the target/release folder.
![grafik](https://user-images.githubusercontent.com/69533520/202490454-dd2bc7c0-88a3-4583-bf57-eb41d28afa05.png)

**Comment by Pokemonplatin** [comment]
I dont trust the exe

**Comment by kaidacoder** [comment]
Thx
Helped me alot

**Comment by 1zun4** [comment]
Why are you even trying to compile it yourself? @kaidacoder
We are offering downloads here:
https://github.com/CCBlueX/LiquidLauncher/actions

**Comment by kaidacoder** [comment]
i dont know

**Comment by kaidacoder** [comment]
umm it said compile it youself so i did

**Comment by kaidacoder** [comment]
where would i find it

**Comment by kaidacoder** [comment]
ok it says its dangerous

**Comment by kaidacoder** [comment]
wait why do you have acces to my microsoft account

**Comment by 1zun4** [comment]
are u trolling

**Comment by kaidacoder** [comment]
![image](https://user-images.githubusercontent.com/109360020/202492406-031065cc-cf85-447d-8d77-bd434941953f.png)

**Comment by 1zun4** [comment]
It is the microsoft login? What are you expecting? Type in the code which is showed on the launcher and login into your microsoft account.

**Comment by kaidacoder** [comment]
what is this

**Comment by kaidacoder** [comment]
is this a virus i mean i have trusted you?

**Comment by kaidacoder** [comment]
@1zun4 you there

**Comment by 1zun4** [comment]
The code is open-source. Look it up yourself. If you do not trust us, do not use it.

**Comment by kaidacoder** [comment]
ok but id do trust you

**Comment by kaidacoder** [comment]
how long did it take you to make this

**Comment by 1zun4** [comment]
It is still in development.

**Comment by kaidacoder** [comment]
ok

**Comment by kaidacoder** [comment]
perfect i get a virus and thret protection message

**Comment by 1zun4** [comment]
happens 🤷🏼‍♂️  the issue is that we are using a unpacker which basically extracts the exe and requires files into a temporary folder and well anti virus softwares do not like that. We have to let this get confirmed by microsoft or figure out something else.

**Comment by kaidacoder** [comment]
ok

**Comment by kaidacoder** [comment]
well thanks and I love liquid bounce its a great client and amazing that its free

**Comment by kaidacoder** [comment]
hey @1zun4 i reported it and got this https://tria.ge/221118-ta5kzahg63/behavioral2#report hmmmmmmmmm

**Comment by kaidacoder** [comment]
i dont know
