### ISSUE TITLE
JRE not found

### ISSUE THREAD

**Issue by guosic** [CCBlueX/LiquidLauncher#153]
Next-Gen can start
![屏幕截图 2023-02-04 103027](https://user-images.githubusercontent.com/101028480/216742003-f43bd0e8-67df-47ef-bd62-7061ae4a2135.png)
Translate with deepl

**Comment by guosic** [comment]
Multiple retries will result in the same error report.
(Translate with deepl)

**Comment by 1zun4** [comment]
Yes noted. This is when there is a JRE folder found, but no JRE inside du to failed download(?). We will fix the issue in the next version., but for now please press "Clear data" and try again, this should solve the issue.

**Comment by guosic** [comment]
> Yes noted. This is when there is a JRE folder found, but no JRE inside due to failed download(?). We will fix the issue in the next version, but for now please press "Clear data" in the settings and try again, this should solve the issue.

Yes, in China sometimes the network connection is unstable, causing the download to fail.(Translate with deepl)
