### ISSUE TITLE
switch to using quilt instead of fabric

### ISSUE THREAD

**Issue by TheAwesome98-Real** [CCBlueX/LiquidLauncher#187]
on the regular (bad) minecraft launcher, i used quilt to load my mods. it's a fork of fabric, with optimisations and more features. quilt supports all fabric mods, but quilt mods don't support fabric, so when i run liquidbounce there are some mods that i can't use with it, which is unfortunate. can you have the launcher download quilt instead of fabric? (i could probably write a pull request to do this because i am familiar with rust, but i want an ok first) maybe you could even add the option to choose between the fabric and quilt mod loader in the program itself.

**Comment by 1zun4** [comment]
Quilt is dead

**Comment by TheAwesome98-Real** [comment]
source?
