### ISSUE TITLE
Allow to use modpacks along with LiquidBounce nextgen

### ISSUE THREAD

**Issue by gabrielvicenteYT** [CCBlueX/LiquidLauncher#191]
This is important for people who want to use certain Optimization Modpacks such as Simply Optimized

**Comment by 1zun4** [comment]
And how are we supposed to do this?

**Comment by gabrielvicenteYT** [comment]
@1zun4 Maybe you could find a way to read .mrpack files?

**Comment by SenkJu** [comment]
I think this might be outside of LiquidLauncher's scope.

**Comment by 1zun4** [comment]
Out of scope
