### ISSUE TITLE
Update the recommended mods

### ISSUE THREAD

**Issue by treatmeniceplz** [CCBlueX/LiquidLauncher#197]
some of the mods that are installed by LiquidLauncher have updates available
a list that mod menu shows 
Fabric Language Kotlin
Mod Menu
Sodium
ViaFabricPlus
Fabric API
i would do this myself but i dont want a non computer savy user to be googling HoW tO UpDaTE MiNeCrAFt MoDs

**Comment by treatmeniceplz** [comment]
ok this is worse than i thought LiquidLauncher Downgrades the mods automatically

**Comment by 1zun4** [comment]
Yes it uses a specific version number that I tested to confirm they are working as intended. I just have to do this more frequent, but it is currently annoying to do because I have no easy way of tracking mod updates.

**Comment by treatmeniceplz** [comment]
Mod menu tells you and the end user about mod updates so you know when to test and for the future tell me where the url to download the mod files so I can test them and if it works fine I will submit a pull request with the source code I don’t have a lot of coding knowledge

**Comment by 1zun4** [comment]
No, I will very soon make an automation for this task.
