### ISSUE TITLE
Not being able to download LiquidBounce with AppImage (Fedora)

### ISSUE THREAD

**Issue by micartey** [CCBlueX/LiquidLauncher#240]
I cannot download LiquidBounce due to the WebView not loading.
In fact, the WebView is completely unresponsive.

**Comment by SenkJu** [comment]
Troubleshooting issues like this is very hard for us. I don't *think* its related to LiquidLauncher itself (working on other Linux distributions). There might be something wrong with your installation?

**Comment by SenkJu** [comment]
Closing this for now.
