### ISSUE TITLE
[BUG] Scripts are very slow

### ISSUE THREAD

**Issue by fineless71** [CCBlueX/LiquidLauncher#241]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

4a5efac

### Operating System

Linux

### Minecraft Version

1.20.4

### Describe the bug

Accessing some Java stuff from scripts (most notably player) kills my FPS, and is unbearably slow. I see a log about `Execution only in interpreted mode will strongly impact the guest application performance.` from GraalVM (but the page it tells me to go to shows "Page not found", of course not LB's fault). Not everything seems to have this issue, some things like `client.displayChatMessage` is fine.

### Steps to reproduce

Try this simple script, it brings me from 60 fps to 1-2 when moving around:
```js
module.on("playerTick", () => {
	if (!mc.player.onGround && mc.player.velocity.y < 0)
		mc.player.velocity.y = 0;
});
```

### Client Log

```shell
[engine] WARNING: The polyglot context is using an implementation that does not support runtime compilation.
The guest application code will therefore be executed in interpreted mode only.
Execution only in interpreted mode will strongly impact the guest application performance.
For more information on using GraalVM see https://www.graalvm.org/java/quickstart/.
To disable this warning the '--engine.WarnInterpreterOnly=false' option or use the '-Dpolyglot.engine.WarnInterpreterOnly=false' system property.
```

**Comment by fineless71** [comment]
I hope this can be fixed another way. The following performs fine for example:
```js
module.on("playerTick", () => {
	client.displayChatMessage("Speed: " + movementUtil.speed());
	client.displayChatMessage("Speed: " + movementUtil.speed());
	client.displayChatMessage("Speed: " + movementUtil.speed());
});
```
What I originally thought was going on is that when mc.player is used, it first needs to convert the entire mc object to js, which is huge and probably takes a while (and maybe even everything it holds), and then player as well. But `onGround` seems to perform *ok-ish*, while velocity is very bad. So I have no idea.

**Comment by 1zun4** [comment]
This has been resolved since Launcher v0.3.0 and Client Version v0.18.0 - it now uses GraalVM and is much faster.

**Comment by fineless71** [comment]
I just tried out liquid launcher and I got the following log:
```
  2024-12-07T21:31:37.113741Z ERROR liquidlauncher::app::gui: [To redirect Truffle log output to a file use one of the following options:
* '--log.file=<path>' if the option is passed using a guest language launcher.
* '-Dpolyglot.log.file=<path>' if the option is passed using the host Java launcher.
* Configure logging using the polyglot embedding API.]
[engine] WARNING: The polyglot engine uses a fallback runtime that does not support runtime compilation to native code.
Execution without runtime compilation will negatively impact the guest application performance.
The following cause was found: JVMCI is not enabled for this JVM. Enable JVMCI using -XX:+EnableJVMCI.
For more information see: https://www.graalvm.org/latest/reference-manual/embed-languages/#runtime-optimization-support.
To disable this warning use the '--engine.WarnInterpreterOnly=false' option or the '-Dpolyglot.engine.WarnInterpreterOnly=false' system property.
```

It looks like `-XX:+EnableJVMCI` just needs to be passed to the JVM. I don't see any way to add custom launch args in liquidlauncher, and it should probably be done by default. I use Arch linux, using the `liquidlauncher-bin` AUR package.

**Comment by fineless71** [comment]
@1zun4 ping because I don't think you saw my message and I think this should be reopened

**Comment by 1zun4** [comment]
So, what happened: We switched to GraalVM and suddenly people complained about extreme lags on Windows, so we has to go back to Temurin. We will introduce a JVM selector for the upcoming update of LiquidLauncher, so you can choose yourself, but we will stick with Temurin JRE because of GraalVM's bad performance on Windows (???).
