### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by luckynolol** [CCBlueX/LiquidLauncher#242]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.1.2

### Operating System

Windows 11

### Minecraft Version

1.20.4 

### Describe the bug

crashing game

### Steps to reproduce

help me

### Client Log

```shell
https://paste.ccbluex.net/8f7987d5d
```

### Screenshots

![LiquidLauncher 31_01_2024 10_45_44 CH](https://github.com/CCBlueX/LiquidBounce/assets/158307682/a3de1aaf-e170-495c-a9cb-935b373baca9)

**Comment by 1zun4** [comment]
can you access https://launchermeta.mojang.com/mc/game/version_manifest.json via your browser, if not fix your internet connection. also check if you have any weird proxy running

**Comment by 1zun4** [comment]
we have nothing to do with the mojang server not responding to you

**Comment by luckynolol** [comment]
a
no my laptop not available weird proxy


Vào Th 4, 31 thg 1, 2024 vào lúc 23:05 1zuna ***@***.***>
đã viết:

**Comment by SenkJu** [comment]
I think this issue is unrelated to LiquidLauncher.
