### ISSUE TITLE
Can't MS Login

### ISSUE THREAD

**Issue by gongis1** [CCBlueX/LiquidLauncher#245]
after i try to log in with my account, it shows this error

`﻿
unable to ms auth: Something went wrong while requesting the Microsoft auth token.
Error: invalid_grant
Description: AADSTS70000: The user could not be authenticated or user interaction is required. The user must sign in again and if needed grant the client application access to the requested scope. Trace ID:
f1e809f1-e095-4a1a-bea5-9f8e75613703 Correlation ID: b1a986c0-babc-4b9b-9a09-e895c7a270da Timestamp:
2024-02-07 04:55:49Z
Timestamp: 2024-02-07 04:55:49Z
Correlation Id: b1a986c0-babc-4b9b-9a09-e895c7a270da Error URI:
https://login.microsoftonline.com/error?code=70000
`

**Comment by SenkJu** [comment]
Have you tried signing in again?

**Comment by SenkJu** [comment]
Closing this for now.
