### ISSUE TITLE
I cant launch liquidbounce

### ISSUE THREAD

**Issue by husi1337** [CCBlueX/LiquidLauncher#250]
An error with the client occourd:
%1: nem Win32 alkalmazás. (os error 193)

I have this error when i click on
Launch LiquidBounce

**Comment by SenkJu** [comment]
Can you please show me a screenshot of the error you are getting?

**Comment by 1zun4** [comment]
Try following this guide: https://liquidbounce.net/docs/Tutorials/Fixing%20LiquidLauncher
