### ISSUE TITLE
ERROR 502

### ISSUE THREAD

**Issue by boboi699** [CCBlueX/LiquidLauncher#259]
facing an error while launching game in liquidlauncher
logs:- An error with the client occourd:
https://launchermeta.mojang.com/ returned with an error code, try again later!

Caused by:
    HTTP status server error (502 Bad Gateway) for url (https://launchermeta.mojang.com/mc/game/version_manifest.json)

**Comment by boboi699** [comment]
i didn't used that shit easymc and is there any way to download that launchermeta.mojang.com?

**Comment by boboi699** [comment]
plz tell me bro i m really despirate to use liquidbounce plzz

**Comment by 1zun4** [comment]
Bro I gave you 3 POSSIBLE SOLUTIONS. Try them first, THEN you can ask again.

**Comment by boboi699** [comment]
there's no option for adding liquidlauncher in firewall and java is already added in firewall

**Comment by boboi699** [comment]
umm will it work if i try downloading minecaft  from thei official minecraft launcher?

**Comment by SenkJu** [comment]
Have you actually checked your hosts file?

**Comment by boboi699** [comment]
no where is it?

**Comment by SenkJu** [comment]
C:\Windows\System32\Drivers\etc\hosts

**Comment by 1zun4** [comment]
Try following this guide: https://liquidbounce.net/docs/Tutorials/Fixing%20LiquidLauncher
