### ISSUE TITLE
offline but online

### ISSUE THREAD

**Issue by czmaster502** [CCBlueX/LiquidLauncher#260]
This is the error it gave me even tho im online: You are offline! Please connect to the internet and restart the app. 
If this problem persists, please contact the developer.

(Error: unable to connect to api.liquidbounce.net: erroe sending request for url
(https://api.liquidbounce.net/): error trying to connect: tcp connect error: A connection attemjpt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060))

It says this, and only works on a vpn
![image](https://github.com/CCBlueX/LiquidLauncher/assets/106103506/ba1565d9-b4f5-49cd-adfb-d4b038bb08b3)

And the liquidbounce.net site also doesnt work for me. Also only on a vpn

**Comment by SenkJu** [comment]
Where are you from?

**Comment by czmaster502** [comment]
> Where are you from?

Czech republic

**Comment by 1zun4** [comment]
It is likely your Windows Firewall is blocking the connection. Please allow the LiquidLauncher in your WF settings.

**Comment by 1zun4** [comment]
Try following this guide: https://liquidbounce.net/docs/Tutorials/Fixing%20LiquidLauncher
