### ISSUE TITLE
Additional mods

### ISSUE THREAD

**Issue by Accomplished-New** [CCBlueX/LiquidLauncher#265]
Hello, I can't get additional mods to work. 
![obraz_2024-03-19_174959903](https://github.com/CCBlueX/LiquidLauncher/assets/111688100/357739a8-78bb-4d04-8a04-acba0a28df7c)
![obraz_2024-03-19_175040376](https://github.com/CCBlueX/LiquidLauncher/assets/111688100/d1970fe3-f324-4bdf-ba14-4da7999de9c4)

**Comment by SenkJu** [comment]
Please paste the log as a text here. I can't translate what it says otherwise.

**Comment by 1zun4** [comment]
No response.
