### ISSUE TITLE
[BUG] Can't launch. Can't Download the client. (LiquidLauncher)

### ISSUE THREAD

**Issue by Davut-A** [CCBlueX/LiquidLauncher#272]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.1.9

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

I was just downloading it then it said [This](https://paste.ccbluex.net/69ec94268)

### Steps to reproduce

- Just click Launch LiquidBounce

### Client Log

```shell
https://paste.ccbluex.net/69ec94268
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/109054538/3981b56d-afef-4eea-b12e-4e3861969a1a)

**Comment by 1zun4** [comment]
No response.
