### ISSUE TITLE
[BUG] Cannot add mod to LiquidBounce

### ISSUE THREAD

**Issue by Rylazius** [CCBlueX/LiquidLauncher#279]
![image](https://github.com/CCBlueX/LiquidLauncher/assets/94881672/7a10b4ae-2947-4d53-a1b7-beac65fcb671)

reproduce:
 1. add mods
 2. launch
 3. done

**Comment by Rylazius** [comment]
more images cuz ok:
![image](https://github.com/CCBlueX/LiquidLauncher/assets/94881672/fa9cfc64-b9ba-48a9-928c-8654d7e50b84)
![image](https://github.com/CCBlueX/LiquidLauncher/assets/94881672/148db657-91b7-42af-8701-e612e9381742)

**Comment by Rylazius** [comment]
plus i already run liquidlauncher as administrator but didnt work

**Comment by BlackFyreBoy** [comment]
I had the same issue if this mod is for a server I recommend joining the server without the mod

**Comment by DataM0del** [comment]
> ![image](https://private-user-images.githubusercontent.com/94881672/318046264-7a10b4ae-2947-4d53-a1b7-beac65fcb671.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MjI3MjAsIm5iZiI6MTczMTQyMjQyMCwicGF0aCI6Ii85NDg4MTY3Mi8zMTgwNDYyNjQtN2ExMGI0YWUtMjk0Ny00ZDUzLWExYjctYmVhYzY1ZmNiNjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE0NDAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyYmIxZjJiYjZhNzVhOWRjM2I5ZDU1NjFkMzI0NjhiYTFmZDM4YjNhY2ExNzhjMjI1ZDA3Mjg2MzE0NThjYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pFTWJGnbhAbXe_nttb5r323sgT6DLeaJgvI6GhtbC3E)
> 
> reproduce:
> 
>     1. add mods
> 
>     2. launch
> 
>     3. done

forge mods :skull:

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidLauncher/releases/tag/v0.4.0

**Comment by Rylazius** [comment]
> > ![image](https://private-user-images.githubusercontent.com/94881672/318046264-7a10b4ae-2947-4d53-a1b7-beac65fcb671.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MjI3MjAsIm5iZiI6MTczMTQyMjQyMCwicGF0aCI6Ii85NDg4MTY3Mi8zMTgwNDYyNjQtN2ExMGI0YWUtMjk0Ny00ZDUzLWExYjctYmVhYzY1ZmNiNjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE0NDAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyYmIxZjJiYjZhNzVhOWRjM2I5ZDU1NjFkMzI0NjhiYTFmZDM4YjNhY2ExNzhjMjI1ZDA3Mjg2MzE0NThjYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pFTWJGnbhAbXe_nttb5r323sgT6DLeaJgvI6GhtbC3E)
> > reproduce:
> > ```
> > 1. add mods
> > 
> > 2. launch
> > 
> > 3. done
> > ```
> 
> forge mods 💀

i just realized after a year LMFAO
