### ISSUE TITLE
Liquid api ssl certificate error

### ISSUE THREAD

**Issue by KekOnTheWorld** [CCBlueX/LiquidLauncher#28]
Looks like the ssl certificate for api.liquidbounce.net is invalid, so i can't launch liquid launcher.

**Comment by 1zun4** [comment]
I am currently working on a new API to make the build system fully automatich and compatibel with the launcher, which required me to update the launcher itself:
https://github.com/CCBlueX/LiquidLauncher/commit/d35ce37dd9faa05f8627cabf9723f8359a6c144c
