### ISSUE TITLE
os error 5

### ISSUE THREAD

**Issue by Murdercakee** [CCBlueX/LiquidLauncher#288]
![image](https://github.com/CCBlueX/LiquidLauncher/assets/164326456/b03c97d4-0d25-4d12-85d5-ad2e32d72296)

**Comment by Murdercakee** [comment]
how to fix??

**Comment by dstalicaa** [comment]
it lauches for you?

**Comment by 1zun4** [comment]
restart computer

**Comment by Murdercakee** [comment]
ty that worked
