### ISSUE TITLE
using half of the cpu memory

### ISSUE THREAD

**Issue by ENDER1355** [CCBlueX/LiquidLauncher#3]
its using half of the cpu memory it also slows the computer and randomly pops up

**Comment by NurMarvin** [comment]
This isn't the current LiquidLauncher, this is a completely new one made from the ground up to make up for the issues that the old one has.

**Comment by ENDER1355** [comment]
> This isn't the current LiquidLauncher, this is a completely new one made from the ground up to make up for the issues that the old one has.

was tun du meinen?
