### ISSUE TITLE
allocating less ram

### ISSUE THREAD

**Issue by vardenixxxas** [CCBlueX/LiquidLauncher#308]
is it possible to make liquidlauncher to allocate less ram than 20%? because some systems have so much ram and for example a system with 128gb could make minecraft crash of excessive ram allocation.

OR

make it possible of instead chosing the allocation of ram by percentage, why not choose the allocation by the system amount
making a slider that lets you choose from x ram to y ram

for example, i have 32 gb of ram and i can choose from 1 to 32 gb of ram allocation

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidLauncher/releases/tag/v0.4.0

**Comment by vardenixxxas** [comment]
hell yeah
