### ISSUE TITLE
When I start Minecraft I get the error Process exited with non-zero exit code: 1.

### ISSUE THREAD

**Issue by ukrmaa122** [CCBlueX/LiquidLauncher#314]
Log.
Loading minecraft version manifest...Downloading recommended mod LiquidBounceDownloading recommended mod Fabric APIDownloading recommended mod Fabric KotlinLoading version profile...Downloading inherited version 1.21...Launching e982523ec0e0729e8c0e6b2a7540c8baec54590a...Setting up...Determined OS to be windows 10.0.19045Checking for JRE...Java Path: "C:\\Users\\bogda\\AppData\\Roaming\\CCBlueX\\LiquidLauncher\\data\\runtimes\\temurin_21\\jdk-21.0.4 7-jre\\bin\\javaw.exe"Client JAR local hash: 0e9a07b9bb3390602f977073aa12884a4ce12431, remote: 0e9a07b9bb3390602f977073aa12884a4ce12431Checking libraries...Library com.google.code.gson:gson:2.10.1 already exists and SHA1 matches.Library com.github.oshi:oshi-core:6.4.10 already exists and SHA1 matches.Library org.ow2.asm:asm-commons:9.6 already exists and SHA1 matches.Library org.ow2.asm:asm:9.6 already exists and SHA1 matches.Library org.ow2.asm:asm-analysis:9.6 already exists and SHA1 matches.Library org.ow2.asm:asm-tree:9.6 already exists and SHA1 matches.Library org.ow2.asm:asm-util:9.6 already exists and SHA1 matches.Library net.fabricmc:sponge-mixin:0.13.3 mixin.0.8.5 already exists and SHA1 matches.Library net.fabricmc:intermediary:1.21 already exists and SHA1 matches.Library net.fabricmc:fabric-loader:0.15.11 already exists and SHA1 matches.Library com.mojang:blocklist:1.0.10 already exists and SHA1 matches.Library com.mojang:patchy:2.2.10 already exists and SHA1 matches.Library com.mojang:logging:1.2.7 already exists and SHA1 matches.Library com.mojang:brigadier:1.2.9 already exists and SHA1 matches.Library com.ibm.icu:icu4j:73.2 already exists and SHA1 matches.Library com.mojang:datafixerupper:8.0.16 already exists and SHA1 matches.Library com.google.guava:failureaccess:1.0.1 already exists and SHA1 matches.Library com.mojang:authlib:6.0.54 already exists and SHA1 matches.Library com.mojang:text2speech:1.17.9 already exists and SHA1 matches.Library com.google.guava:guava:32.1.2-jre already exists and SHA1 matches.Library commons-codec:commons-codec:1.16.0 already exists and SHA1 matches.Library io.netty:netty-common:4.1.97.Final already exists and SHA1 matches.Library io.netty:netty-codec:4.1.97.Final already exists and SHA1 matches.Library io.netty:netty-handler:4.1.97.Final already exists and SHA1 matches.Library io.netty:netty-buffer:4.1.97.Final already exists and SHA1 matches.Library io.netty:netty-resolver:4.1.97.Final already exists and SHA1 matches.Library commons-logging:commons-logging:1.2 already exists and SHA1 matches.Library commons-io:commons-io:2.15.1 already exists and SHA1 matches.Library io.netty:netty-transport-classes-epoll:4.1.97.Final already exists and SHA1 matches.Library io.netty:netty-transport-native-unix-common:4.1.97.Final already exists and SHA1 matches.Library it.unimi.dsi:fastutil:8.5.12 already exists and SHA1 matches.Library io.netty:netty-transport:4.1.97.Final already exists and SHA1 matches.Library net.sf.jopt-simple:jopt-simple:5.0.4 already exists and SHA1 matches.Library net.java.dev.jna:jna-platform:5.14.0 already exists and SHA1 matches.Library net.java.dev.jna:jna:5.14.0 already exists and SHA1 matches.Library org.apache.commons:commons-compress:1.26.0 already exists and SHA1 matches.Library org.apache.commons:commons-lang3:3.14.0 already exists and SHA1 matches.Library org.apache.httpcomponents:httpcore:4.4.16 already exists and SHA1 matches.Library org.apache.logging.log4j:log4j-api:2.22.1 already exists and SHA1 matches.Library org.apache.httpcomponents:httpclient:4.5.13 already exists and SHA1 matches.Library org.jcraft:jorbis:0.0.17 already exists and SHA1 matches.Library org.apache.logging.log4j:log4j-core:2.22.1 already exists and SHA1 matches.Library org.apache.logging.log4j:log4j-slf4j2-impl:2.22.1 already exists and SHA1 matches.Library org.lwjgl:lwjgl-freetype:3.3.3:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl-freetype:3.3.3:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl-freetype:3.3.3:natives-windows-x86 already exists and SHA1 matches.Library org.joml:joml:1.10.5 already exists and SHA1 matches.Library org.lwjgl:lwjgl-glfw:3.3.3 already exists and SHA1 matches.Library org.lwjgl:lwjgl-glfw:3.3.3:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl-freetype:3.3.3 already exists and SHA1 matches.Library org.lwjgl:lwjgl-glfw:3.3.3:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl-glfw:3.3.3:natives-windows-x86 already exists and SHA1 matches.Library org.lwjgl:lwjgl-jemalloc:3.3.3 already exists and SHA1 matches.Library org.lwjgl:lwjgl-openal:3.3.3 already exists and SHA1 matches.Library org.lwjgl:lwjgl-openal:3.3.3:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl-jemalloc:3.3.3:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl-jemalloc:3.3.3:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl-jemalloc:3.3.3:natives-windows-x86 already exists and SHA1 matches.Library org.lwjgl:lwjgl-openal:3.3.3:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl-openal:3.3.3:natives-windows-x86 already exists and SHA1 matches.Library org.lwjgl:lwjgl-opengl:3.3.3:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl-stb:3.3.3:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl-opengl:3.3.3 already exists and SHA1 matches.Library org.lwjgl:lwjgl-opengl:3.3.3:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl-opengl:3.3.3:natives-windows-x86 already exists and SHA1 matches.Library org.lwjgl:lwjgl-stb:3.3.3 already exists and SHA1 matches.Library org.lwjgl:lwjgl-stb:3.3.3:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl-stb:3.3.3:natives-windows-x86 already exists and SHA1 matches.Library org.lwjgl:lwjgl-tinyfd:3.3.3:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl-tinyfd:3.3.3 already exists and SHA1 matches.Library org.lwjgl:lwjgl-tinyfd:3.3.3:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl-tinyfd:3.3.3:natives-windows-x86 already exists and SHA1 matches.Library org.lwjgl:lwjgl:3.3.3 already exists and SHA1 matches.Library org.lwjgl:lwjgl:3.3.3:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl:3.3.3:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl:3.3.3:natives-windows-x86 already exists and SHA1 matches.Library org.lz4:lz4-java:1.8.0 already exists and SHA1 matches.Library org.slf4j:slf4j-api:2.0.9 already exists and SHA1 matches.Checking assets...Launching...Running...An error occourd:

Process exited with non-zero exit code: 1.

**Comment by 1zun4** [comment]
Incomplete log
