### ISSUE TITLE
Unable to open the launcher

### ISSUE THREAD

**Issue by Bzdhyp** [CCBlueX/LiquidLauncher#320]
I reinstalled a simple version of the system and then I can't open the launcher

**Comment by 1zun4** [comment]
You are likely missing core features such as Edge. Use a standard installation of Windows instead.

**Comment by greatmice** [comment]
> You are likely missing core features such as Edge. Use a standard installation of Windows instead.

Is Edge the only core feature or are there other dependencies?

**Comment by 1zun4** [comment]
> > You are likely missing core features such as Edge. Use a standard installation of Windows instead.
> 
> Is Edge the only core feature or are there other dependencies?

See https://liquidbounce.net/docs/Tutorials/Fixing%20LiquidLauncher

### LiquidLauncher does not show up (Windows)

This is a known issue if you've previously uninstalled Microsoft Edge or used so-called Windows debloat tools. LiquidLauncher uses [Edge Webview2](https://developer.microsoft.com/de-de/microsoft-edge/webview2/) to run - which is a core feature of your Windows operating system.

To fix this problem, you can simply download and install [Microsoft Webview2](https://developer.microsoft.com/de-de/microsoft-edge/webview2/?form=MA13LH#download). After that, your launcher will appear as expected.
