### ISSUE TITLE
1.20.1 Switch to version 1.8.9, but you cannot switch to other versions after the switchover, and an error message is displayed

### ISSUE THREAD

**Issue by 115414niubi** [CCBlueX/LiquidLauncher#322]
Process exited with non-zero exit code: 7900.

Try restarting the LiquidLauncher with administrator rights.
If this error persists, upload your log with the button below and report it to GitHub.

**Comment by 115414niubi** [comment]
_updateTitleProperties:animated:] + 186
	10  CoreFoundation                      0x00007ff81aa1268c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	11  CoreFoundation                      0x00007ff81aaafaa2 ___CFXRegistrationPost_block_invoke + 49
	12  CoreFoundation                      0x00007ff81aaafa20 _CFXRegistrationPost + 496
	13  CoreFoundation                      0x00007ff81a9e42f8 _CFXNotificationPost + 735
	14  Foundation                          0x00007ff81b8237ce -[NSNotificationCenter postNotificationName:object:userInfo:] + 82
	15  AppKit                              0x00007ff81db7320e -[NSWindowTitleController _propertiesChanged:] + 147
	16  AppKit                              0x00007ff81d49d7ca -[NSWindow _dosetTitle:andDefeatWrap:] + 215
	17  libglfw.dylib                  
An error occourd:

Process exited with non-zero exit code: 7900.

**Comment by 1zun4** [comment]
No idea what this is supposed to mean.
