### ISSUE TITLE
[Feature Request] Add oresim as a bypass for anti x-ray | Update to 1.21.4 eta?

### ISSUE THREAD

**Issue by vanvac** [CCBlueX/LiquidLauncher#324]
would love to see a ore sim like module that uses the world seed to simulate where ores would generate. (oresim is a module in meteor rejects which is an addon for meteor client)

**Comment by 1zun4** [comment]
No ETA for 1.21.3 - but you can use LiquidBounce on 1.21.3 already using ViaFabricPlus. It has recently been updated with fixes.

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidLauncher/releases/tag/v0.4.0
