### ISSUE TITLE
just a questions 

### ISSUE THREAD

**Issue by om3ga6400** [CCBlueX/LiquidLauncher#327]
objectively, is this better than meteor, also what are the major differences?

**Comment by 1zun4** [comment]
LiquidBounce is much more active in development, focusing on anti-cheat bypasses and offering a greater variety of custom themes and designs, scripts and so on. It may depend on your use case which one you prefer, but it's worth a try. If you find something that is missing on LiquidBounce, you can request it here: https://github.com/CCBlueX/LiquidBounce/issues

**Comment by om3ga6400** [comment]
dose it have or support baritone?

**Comment by 1zun4** [comment]
> dose it have or support baritone?

LiquidBounce is based on Minecraft 1.21.1, so only if Baritone supports it. Official Baritone does not seem to get updates, but I think there are updated versions of it available. Back in 1.20.4 it was bundled with LiquidBounce via LiquidLauncher, but not anymore.

**Comment by om3ga6400** [comment]
> > dose it have or support baritone?
> 
> LiquidBounce is based on Minecraft 1.21.1, so only if Baritone supports it. Official Baritone does not seem to get updates, but I think there are updated versions of it available. Back in 1.20.4 it was bundled with LiquidBounce via LiquidLauncher, but not anymore.
> 
> Edit: https://github.com/cabaletta/baritone/commits/1.21.1 - Seems like Baritone for Minecraft 1.21.1 exists.

what abt meator fork of bar

**Comment by 1zun4** [comment]
> > > dose it have or support baritone?
> > 
> > 
> > LiquidBounce is based on Minecraft 1.21.1, so only if Baritone supports it. Official Baritone does not seem to get updates, but I think there are updated versions of it available. Back in 1.20.4 it was bundled with LiquidBounce via LiquidLauncher, but not anymore.
> > Edit: https://github.com/cabaletta/baritone/commits/1.21.1 - Seems like Baritone for Minecraft 1.21.1 exists.
> 
> what abt meator fork of bar

I don't know what you mean.

**Comment by om3ga6400** [comment]
> > > > dose it have or support baritone?
> > > 
> > > 
> > > LiquidBounce is based on Minecraft 1.21.1, so only if Baritone supports it. Official Baritone does not seem to get updates, but I think there are updated versions of it available. Back in 1.20.4 it was bundled with LiquidBounce via LiquidLauncher, but not anymore.
> > > Edit: https://github.com/cabaletta/baritone/commits/1.21.1 - Seems like Baritone for Minecraft 1.21.1 exists.
> > 
> > 
> > what abt meator fork of bar
> 
> I don't know what you mean.

the meteor client fork of barritone
