### ISSUE TITLE
[Bug?] After compiling, app doesn't start

### ISSUE THREAD

**Issue by NONPLAYT** [CCBlueX/LiquidLauncher#99]
LiquidBounce Build/Version
Launcher

Operating System
Windows

Minecraft Version
Not valid.

Describe the bug
After compiling the source and running liquidlauncher.exe, app doesn't starts and nothing happening (I don't know if this is a bug or not)

Screenshots
no

**Comment by 1zun4** [comment]
It requires Sciter DLL
